plan_record.type.*:
  type: config_entity
  label: 'Plan record relationship type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
